services:

  app:
    build: .
    ports:
      - 3000:3001
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  db:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_ROOT_PASSWORD: example
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: routes
