services:
  database:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_ROOT_PASSWORD: example
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: routes